### ISSUE TITLE
HTTP or SOCKS proxy support

### ISSUE THREAD

**Issue by feeops** [dyc3/steamguard-cli#177]
can you support http or socks proxy?

**Comment by dyc3** [comment]
If you can come up with a use case that's not "avoiding Valve's rate limits" or "I have 3 billion steam accounts for some reason" I would be happy to accept contributions to add that.

Otherwise, I don't see how this is useful for anybody other than scammers and spammers, which is something I do not want to facilitate.

**Comment by feeops** [comment]
I am in China.China network block steam website.

> If you can come up with a use case that's not "avoiding Valve's rate limits" or "I have 3 billion steam accounts for some reason" I would be happy to accept contributions to add that.
> 
> Otherwise, I don't see how this is useful for anybody other than scammers and spammers, which is something I do not want to facilitate.

I am in China.China ISP network block steam website.
