### ISSUE TITLE
remove: Does not prompt to log in if access token is invalid

### ISSUE THREAD

**Issue by AndriiSeeker** [dyc3/steamguard-cli#256]
### Version

0.9.5

### What happened?

Help me please! 
I try to remove the mobile authenticator from my account. I passed the command "./steamguard -u andriy2004 remove".
But I got error: ERROR - Unexpected error when removing authenticator from andriy2004: Unauthorized: Access token is missing or invalid.
![image](https://github.com/dyc3/steamguard-cli/assets/113901127/5d6dc209-d106-42e9-8ad0-b7f432b75d46)

**Comment by dyc3** [comment]
Please run it with `-v debug` and post the output.

**Comment by AndriiSeeker** [comment]
![image](https://github.com/dyc3/steamguard-cli/assets/113901127/0c995ada-bf61-4e07-99c3-5ab9f6afebf4)

**Comment by dyc3** [comment]
This is definitely a bug with how steamguard-cli handles errors in this situation. It'll be fixed in the next release.

FYI, if you're trying to transfer the authenticator to your phone, there's a method to transfer it through the steam mobile app. Just try to add an authenticator in the mobile app and it'll walk you through it.

**Comment by AndriiSeeker** [comment]
Man, how much do you need to fix it? Thanks.

**Comment by dyc3** [comment]
Shouldn't take too long to fix. The next release will definitely be out by the end of the day, but likely sooner.

**Comment by dyc3** [comment]
This should be fixed in `v0.9.6`.

**Comment by AndriiSeeker** [comment]
Do I need to redownload it?

**Comment by dyc3** [comment]
Yes
