### ISSUE TITLE
Issue with command

### ISSUE THREAD

**Issue by GreenSlacer** [dyc3/steamguard-cli#50]
when i want to do an action like steamguard code name
 i get prompted to "steamguard: command not found"

**Comment by Pingger** [comment]
you might want to try `./steamguard` ...

**Comment by GreenSlacer** [comment]
oh okay that actually worked thanks! , kinda new to linux and somehow had revive my pc withot losing steamauth on windows :P

**Comment by Pingger** [comment]
ok, here some small info to binaries/executables in Linux:
To run a binary in your current folder you need to specify `./`, otherwise Linux will only check its "known" commands from the `$PATH` variable. 

Additionally you might come accross binaries, that are not registered as executable. Linux will refuse to execute those binaries unless you tell it, that the given binary is in fact executable. usually you would `chmod +x "filename"` to that. This command marks a file as executable and would then allow you to `./filename` to run it. Keep in mind, if that file is not intended by its creator to be executed , this usually just gives you an error, than Linux does not know how to actually run the file

**Comment by laptopmutia** [comment]
I installed the application using .deb file and it returns `steamguard-cli: command not found`

how to add the executable from .deb files?

**Comment by dyc3** [comment]
The cannonical way to run steamguard cli is with `steamguard`, not `steamguard-cli`. Due to a limitation with cargo, it can't change the name of the binary when you use `cargo install`.
